version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: first
    volumes:
      - db_data:/var/lib/mysql
      - db_logs:/var/log/mysql
    networks:
      app_network:
        ipv4_address: 10.10.0.2

  web:
    build: .
    container_name: web_container
    environment:
      DB_HOST: 10.10.0.2
      DB_NAME: first
      DB_USER: root
      DB_PASSWORD: 1
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - web_data:/var/www/html
      - web_logs:/var/log/apache2
    networks:
      app_network:
        ipv4_address: 10.10.0.3

  nginx:
    image: nginx:1.18
    container_name: nginx_container
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      app_network:
        ipv4_address: 10.10.0.4

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16

volumes:
  db_data:
  db_logs:
  web_data:
  web_logs:
